CREATE TABLE anniv_list (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  month TINYINT UNSIGNED,
  day TINYINT UNSIGNED,
  description VARCHAR(255),
  registration_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE(name, month, day)
);
